all:	main.cpp init.cpp out.cpp stdnet.cpp precv.cpp hello.cpp dd.cpp lsr.cpp lsu.cpp lsack.cpp pkt.cpp errlog.cpp genrt.cpp
	g++ -o /home/james/NetBeansProjects/ospf0.659/dist/Debug/GNU-Linux-x86/ospf0.659 main.cpp init.cpp out.cpp stdnet.cpp hello.cpp dd.cpp lsr.cpp lsu.cpp lsack.cpp pkt.cpp precv.cpp errlog.cpp genrt.cpp -pthread -g
clean:
	rm /home/james/NetBeansProjects/ospf0.659/dist/Debug/GNU-Linux-x86/ospf0.659
